Move the update readme higher in the process, dynamically recurse for the dll

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -43,6 +43,12 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y powershell
 
+      - name: Update README using custom action
+        uses: mod-posh/UpdateReadme@main
+        with:
+          project_name: "${{ vars.PROJECT_NAME }}"
+          verbose: true
+
       - name: Install XMLDocMD Tool
         run: dotnet tool install --global xmldocmd
 
@@ -54,6 +60,19 @@ jobs:
       
       - name: Push to NuGet
         run: dotnet nuget push ./publish/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
+
+      - name: Find and Copy DLL to Publish Folder
+        shell: pwsh
+        run: |
+          $dllPath = Get-ChildItem -Path . -Recurse -Directory | Where-Object { $_.Name -eq "bin" } |
+                     Get-ChildItem -Recurse -Filter "${{ vars.PROJECT_NAME }}.dll" -File |
+                     Select-Object -First 1
+          if (-not $dllPath) {
+            Write-Error "Error: DLL not found!"
+            exit 1
+          }
+          Write-Output "Found DLL at: $dllPath"
+          Copy-Item -Path $dllPath.FullName -Destination "./publish/"
 
       - name: Generate Documentation
         run: |
@@ -75,9 +94,4 @@ jobs:
           git commit -m "Update documentation for release v${{ env.VERSION }}"
           git push origin ${{ github.ref_name }}
         if: success()
-
-      - name: Update README using custom action
-        uses: mod-posh/UpdateReadme@main
-        with:
-          project_name: "${{ vars.PROJECT_NAME }}"
-          verbose: true
+        
